@startuml use-case
left to right direction

actor Felhasználó as user
actor Vendég as guest

package "Bejelentkezés/Regisztráció" {
    
    usecase "Bejelentkezés" as Login
    usecase "Regisztráció" as register
}
guest -> register
guest -> Login
user -> Login

package "Receptek" {
    usecase "recept megtekintés" as viewRecipe

    usecase "Recept hozzáadás" as addRecipe

    usecase "Recept hozzáadás URL-ből" as addRecipeURL
    addRecipe --|> addRecipeURL : <<includes>>

    usecase "Recept hozzáadás manuálisan" as addRecipeManual
    addRecipe --|> addRecipeManual : <<includes>>

    usecase "Receptgyűjtemény  kezelés" as collectionManagement

    usecase "Gyüjteményhez adás" as addRecipeToCollection
    collectionManagement --> addRecipeToCollection
    
    usecase "Gyüjteményből törlés" as deleteRecipeFromCollection
    collectionManagement --> deleteRecipeFromCollection
}

user --> viewRecipe
user --> addRecipe  
user --> collectionManagement

package "Bevásárló lista"{
    usecase "Bevásárló lista megtekinése" as viewShoppinglist
    user -> viewShoppinglist

    usecase "Bevásárló listához adás" as addToShoppinglist
    user -> addToShoppinglist
    
    usecase "Bevásárló listából törlés" as deleteFromShoppinglist
    user -> deleteFromShoppinglist
}

viewRecipe --> addToShoppinglist : <<includes>>

@enduml